import { describe, expect, it } from 'vitest';
import { changedFiles, fromFiles, isEmptyData, stableJson, toFiles } from './files';
import { projectMarkdown, readableFiles, safeName } from './readable';
import { commitMessage, countUnpushed } from './changes';
import { data, doc, item, project } from '../domain/testkit';
import { crossOut } from '../domain/lifecycle';
import { editText, setFolded, moveProject } from '../domain/edits';
import { emptyData } from '../domain/model';

const NOW = '2026-10-02T09:00:00.000+02:00';

const sample = () =>
  data([
    doc(project('p1', { title: 'Grant proposal' }), [
      item('t', { text: 'Draft introduction', due: '2026-10-10', order: 'a' }),
      item('n', { type: 'note', parent: 't', text: 'Use the 2024 call text\nsecond line', order: 'a' }),
      item('d', { text: 'Book room', crossed: true, crossedAt: '2026-09-30T08:00:00+02:00', order: 'b' }),
    ]),
    doc(project('p2', { title: 'Teaching' })),
  ]);

describe('repo files (spec §3)', () => {
  it('writes sorted keys, 2-space indent and a final newline', () => {
    expect(stableJson({ b: 1, a: { d: 2, c: [3] } })).toBe('{\n  "a": {\n    "c": [\n      3\n    ],\n    "d": 2\n  },\n  "b": 1\n}\n');
  });

  it('lays out index, one file per Project, weekly Change-log files and readable copies', () => {
    const d = crossOut(sample(), 'p1', 't', NOW, 'Laptop');
    expect(Object.keys(toFiles(d)).sort()).toEqual([
      'data/changelog/2026-W40.json',
      'data/index.json',
      'data/projects/p1.json',
      'data/projects/p2.json',
      'readable/Grant proposal.md',
      'readable/Teaching.md',
    ]);
  });

  it('round-trips: files → data → the same files', () => {
    const d = crossOut(sample(), 'p1', 't', NOW, 'Laptop');
    const f = toFiles(d);
    expect(fromFiles(f)).toEqual(d);
    expect(toFiles(fromFiles(f))).toEqual(f);
  });

  it('lists changed and removed files', () => {
    const a = toFiles(sample());
    const b = toFiles(editText(sample(), 'p1', 't', 'New text', NOW));
    expect(Object.keys(changedFiles(a, b)).sort()).toEqual(['data/projects/p1.json', 'readable/Grant proposal.md']);
    const { p2: _gone, ...docs } = sample().docs;
    expect(changedFiles(a, toFiles({ ...sample(), docs }))['data/projects/p2.json']).toBeNull();
  });

  it('knows empty data', () => {
    expect(isEmptyData(emptyData())).toBe(true);
    expect(isEmptyData(sample())).toBe(false);
  });
});

describe('readable copy (spec §3.4)', () => {
  it('formats a Project as Markdown in display order', () => {
    expect(projectMarkdown(sample().docs.p1)).toBe(
      [
        '# Grant proposal',
        '',
        '_Next deadline: 10 Oct 2026 · generated by PersonalNote, do not edit_',
        '',
        '- [ ] Draft introduction — due 2026-10-10',
        '  - Use the 2024 call text',
        '    second line',
        '- [x] ~~Book room~~ — crossed out 2026-09-30',
        '',
      ].join('\n'),
    );
  });

  it('makes titles safe file names and numbers duplicates', () => {
    expect(safeName('a/b: c?')).toBe('a-b- c-');
    expect(safeName('  ...  ')).toBe('Untitled');
    const d = data([doc(project('x', { title: 'Same', created: '1' })), doc(project('y', { title: 'same', created: '2' }))]);
    expect(Object.keys(readableFiles(d))).toEqual(['readable/Same.md', 'readable/same (2).md']);
  });
});

describe('unpushed count and commit message (spec §2.2, §6.3)', () => {
  it('counts changed records, ignoring folds', () => {
    const base = sample();
    expect(countUnpushed(base, base)).toBe(0);
    expect(countUnpushed(base, setFolded(base, 'p1', 't', true, NOW))).toBe(0);
    const edited = editText(editText(base, 'p1', 't', 'x', NOW), 'p1', 'd', 'y', NOW);
    expect(countUnpushed(base, edited)).toBe(2);
    expect(countUnpushed(base, moveProject(base, 'p2', 0, NOW))).toBe(1);
  });

  it('says which device, which Projects and how many changes', () => {
    const base = sample();
    expect(commitMessage('Phone', base, editText(base, 'p1', 't', 'x', NOW))).toBe('Phone: Grant proposal (1 change)');
    expect(commitMessage('Laptop', base, setFolded(base, 'p1', 't', true, NOW))).toBe('Laptop: folds (folds only)');
    const removed = { ...base, docs: { p1: base.docs.p1 } };
    expect(commitMessage('Laptop', base, removed)).toBe('Laptop: Teaching (1 change)');
  });
});
