// Spec §3.4: the read-only Markdown copy of each Project, regenerated on every Push for reading on github.com.
import type { AppData, Item, ProjectDoc } from '../domain/model';
import { children, projectDeadline } from '../domain/ordering';

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const longDate = (d: string) => `${+d.slice(8, 10)} ${MONTHS[+d.slice(5, 7) - 1]} ${d.slice(0, 4)}`;

/** A title made safe as a file name on every OS; never empty. */
export function safeName(title: string): string {
  const s = title
    .replace(/[\\/:*?"<>|#%\u0000-\u001f]/g, '-')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/[. ]+$/, '');
  return s || 'Untitled';
}

function itemLines(doc: ProjectDoc, it: Item, depth: number): string[] {
  const pad = '  '.repeat(depth);
  const [first, ...rest] = it.text.split('\n');
  const text = it.crossed ? `~~${first}~~` : first;
  const box = it.type === 'task' ? (it.crossed ? '[x] ' : '[ ] ') : '';
  const extras = [
    it.type === 'task' && it.due && `due ${it.due}`,
    it.crossed && it.crossedAt && `crossed out ${it.crossedAt.slice(0, 10)}`,
  ].filter(Boolean);
  const out = [`${pad}- ${box}${text}${extras.length ? ` — ${extras.join(', ')}` : ''}`];
  for (const line of rest) out.push(`${pad}  ${line}`);
  for (const c of children(doc, it.id)) out.push(...itemLines(doc, c, depth + 1));
  return out;
}

export function projectMarkdown(doc: ProjectDoc): string {
  const p = doc.project;
  const deadline = projectDeadline(doc);
  const lines = [
    p.crossed ? `# ~~${p.title}~~` : `# ${p.title}`,
    '',
    `_${deadline ? `Next deadline: ${longDate(deadline)} · ` : ''}generated by PersonalNote, do not edit_`,
    '',
  ];
  for (const it of children(doc, null)) lines.push(...itemLines(doc, it, 0));
  return lines.join('\n') + '\n';
}

/** readable/<title>.md for every Project; equal titles get " (2)", " (3)"… in a stable order. */
export function readableFiles(data: AppData): Record<string, string> {
  const out: Record<string, string> = {};
  const taken = new Set<string>();
  const docs = Object.values(data.docs).sort((a, b) =>
    a.project.created < b.project.created ? -1 : a.project.created > b.project.created ? 1 : a.project.id < b.project.id ? -1 : 1,
  );
  for (const doc of docs) {
    const name = safeName(doc.project.title);
    let candidate = name;
    for (let n = 2; taken.has(candidate.toLowerCase()); n++) candidate = `${name} (${n})`;
    taken.add(candidate.toLowerCase());
    out[`readable/${candidate}.md`] = projectMarkdown(doc);
  }
  return out;
}
